### ISSUE TITLE
How to find out if an app is running in background?

### ISSUE THREAD

**Issue by Hocceruser** [SuperFreezeApp/SuperFreeze#1]
In newer versions of Android it is not possible to find out if an other app is running in the background, see https://issuetracker.google.com/issues/37091475. 

However, somehow the app Greenify seems to actually find it out, the apps are sorted by running/not running rightfully. Does someone have any idea how?

**Comment by skinzor** [comment]
I've started to learn java / android app development (about 1-2 weeks ago, following udacity course for begginers) so i can't help you, but did you see this? https://stackoverflow.com/a/41769341

I've searched for "nougat java check if app is running in background".

**Comment by Hocceruser** [comment]
I'll do it like this for now:
Only apps that the user launched since the last freeze are shown.
This is not a perfect solution but it will do for now. See #3 (Pull request).

**Comment by Hocceruser** [comment]
Still, if somebody has a better solution or knows how Greenify solved this, I'd be interested.

**Comment by Hocceruser** [comment]
Please see the GitLab page.
